name: isar_projects
description: A new Flutter project.
 
publish_to: 'none' 
 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod:
  isar: ^2.2.1  
  isar_flutter_libs: 2.2.1
  path_provider: 

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter   

  isar_generator: 2.2.1
  build_runner:

  flutter_lints: ^1.0.0
 
flutter:
 
  uses-material-design: true 